# Generated by Django 4.1.3 on 2022-11-18 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI2',
            fields=[
                ('interval_start_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('interval_end_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('cell_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number_of_unique_users', models.IntegerField(default=0)),
                ('interval', models.CharField(blank=True, choices=[('1H', '1-hour'), ('5M', '5-minute')], default=None, max_length=2, null=True)),
            ],
        ),
    ]
