# Generated by Django 4.1.3 on 2022-11-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI2', '0002_alter_kpi2_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi2',
            name='interval_end_timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi2',
            name='interval_start_timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
