# Generated by Django 4.1.3 on 2022-11-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi1',
            name='id',
        ),
        migrations.AddField(
            model_name='kpi1',
            name='interval_end_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi1',
            name='interval_start_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi1',
            name='service_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='kpi1',
            name='total_bytes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi1',
            name='interval',
            field=models.CharField(blank=True, choices=[('1H', '1-hour'), ('5M', '5-minute')], max_length=2, null=True),
        ),
    ]
