# Generated by Django 4.1.3 on 2022-11-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi1',
            name='interval',
            field=models.CharField(blank=True, choices=[('1-hour', 'One Hour'), ('5-minutes', 'Five Minute')], max_length=10, null=True),
        ),
    ]
